import string

SUMMARIZE_FILE_DIFF = string.Template(
    "## GitHub PR Title\n"
    "${title}\n"
    "## Description\n"
    "```\n"
    "${description}\n"
    "```\n"
    "## Diff\n"
    "```\n"
    "diff ${file_diff}\n"
    "```\n"
    "## Instructions\n"
    "I would like you to succinctly summarize the diff within 100 words.\n"
    "If applicable, your summary should include a note about alterations "
    "to the signatures of exported functions, global data structures and "
    "variables, and any changes that might affect the external interface or "
    "behavior of the code."
)

TRIAGE_FILE_DIFF = string.Template(
    "Below the summary, I would also like you to triage the diff as "
    "`NEEDS_REVIEW` or `APPROVED` based on the following criteria:\n\n"
    "- If the diff involves any modifications to the logic or functionality, even if they "
    "seem minor, triage it as `NEEDS_REVIEW`. This includes changes to control structures, "
    "function calls, or variable assignments that might impact the behavior of the code.\n"
    "- If the diff only contains very minor changes that don't affect the code logic, such as "
    "fixing typos, formatting, or renaming variables for clarity, triage it as `APPROVED`.\n\n"
    "Please evaluate the diff thoroughly and take into account factors such as the number of "
    "lines changed, the potential impact on the overall system, and the likelihood of "
    "introducing new bugs or security vulnerabilities. "
    "When in doubt, always err on the side of caution and triage the diff as `NEEDS_REVIEW`.\n\n"
    "You must strictly follow the format below for triaging the diff:\n"
    "[TRIAGE]: <NEEDS_REVIEW or APPROVED>\n\n"
    "Important:\n"
    "- In your summary do not mention that the file needs a thorough review or caution about "
    "potential issues.\n"
    "- Do not provide any reasoning why you triaged the diff as `NEEDS_REVIEW` or `APPROVED`.\n"
    "- Do not mention that these changes affect the logic or functionality of the code in "
    "the summary. You must only use the triage status format above to indicate that."
)

SUMMARIZE_CHANGESETS = string.Template(
    "Provided below are changesets in this pull request. Changesets "
    "are in chronological order and new changesets are appended to the "
    "end of the list. The format consists of filename(s) and the summary "
    "of changes for those files. There is a separator between each changeset. "
    "Your task is to deduplicate and group together files with "
    "related/similar changes into a single changeset. Respond with the updated "
    "changesets using the same format as the input.\n\n"
    "${raw_summary}"
)

SUMMARIZE_PREFIX = string.Template(
    "Here is the summary of changes you have generated for files:\n"
    "```\n"
    "${raw_summary}\n"
    "```"
)

SUMMARIZE_SHORT = string.Template(
    """
    Your task is to provide a concise summary of the changes. This 
    summary will be used as a prompt while reviewing each file and must be very clear for 
    the AI bot to understand. 

    Instructions:

    - Focus on summarizing only the changes in the PR and stick to the facts.
    - Do not provide any instructions to the bot on how to perform the review.
    - Do not mention that files need a through review or caution about potential issues.
    - Do not mention that these changes affect the logic or functionality of the code.
    - The summary should not exceed 500 words.
"""
)

REVIEW_FILE_DIFF = string.Template(
    "## GitHub PR Title\n\n"
    "`$title`\n\n"
    "## Description\n\n"
    "```\n"
    "$description\n"
    "```\n\n"
    "## Summary of changes\n\n"
    "```\n"
    "$short_summary\n"
    "```\n\n"
    "## CRITICAL Instructions - READ CAREFULLY\n\n"
    "You will see code changes in this format:\n"
    "- `---new_hunk---`: The NEW CODE section with ACTUAL file line numbers\n"
    "  - Lines marked `[NEW]` are NEWLY ADDED code - REVIEW THESE\n"
    "  - Lines WITHOUT `[NEW]` are unchanged context lines - DO NOT REVIEW\n"
    "  - ALL line numbers are ACTUAL line numbers from the file\n"
    "- `---old_hunk---`: The OLD CODE (removed/replaced) - for context only\n\n"
    "IMPORTANT:\n"
    "- ONLY review and comment on lines marked with `[NEW]`\n"
    "- DO NOT comment on context lines (lines without `[NEW]`)\n"
    "- DO NOT comment on code from `---old_hunk---` section\n"
    "- Use the EXACT line numbers shown when writing your comments\n\n"
    "Task: Review lines marked `[NEW]` for substantive issues.\n"
    "Output: Review comments in markdown with EXACT line number ranges.\n"
    "Line numbers must match those shown in the new_hunk section.\n"
    "Start and end line numbers must be within the same hunk.\n"
    "For single-line comments, start=end line number.\n"
    "Must use example response format below. You cannot use any other format.\n"
    "People's life depends on it.\n"
    "Use fenced code blocks using the relevant language identifier where applicable.\n"
    "Don't annotate code snippets with line numbers. Format and indent code correctly.\n"
    "Do not use `suggestion` code blocks.\n"  # TODO play with suggestions
    "For fixes, use `diff` code blocks, marking changes with `+` or `-`.\n"
    "The line number range for comments with fix snippets must exactly match the range to replace in the new hunk.\n\n"
    "- Do NOT provide general feedback, summaries, explanations of changes, or praises for making good additions.\n"
    "- You MUST NOT provide any information. ONLY respond using example response format below.\n"
    "- Focus solely on offering specific, objective insights based on the given context and refrain "
    "from making broad comments about potential impacts on the system or question intentions behind the changes.\n\n"
    "If there are no issues found on a line range, simply don't include that line range in your response.\n\n"
    "If you find a particularly elegant or clever solution, you may respond with \"Neat!\" for that line range.\n\n"
    "## Example\n\n"
    "### Example changes\n\n"
    "---new_hunk---  ← THIS IS THE NEW CODE TO REVIEW\n"
    "```\n"
    "18:   z = x / y\n"
    "19:     return z\n"
    "20: \n"
    "21: [NEW] def add(x, y):\n"
    "22: [NEW]     z = x + y\n"
    "23: [NEW]     return z\n"
    "24: \n"
    "25: [NEW] def multiply(x, y):\n"
    "26: [NEW]     return x * y\n"
    "27: \n"
    "28: def subtract(x, y):\n"
    "29:   z = x - y\n"
    "```\n\n"
    "---old_hunk---  ← THIS IS OLD CODE FOR CONTEXT ONLY - DO NOT REVIEW THIS\n"
    "```\n"
    "z = x / y\n"
    "return z\n\n"
    "\n"
    "def add(x, y):\n"
    "    return x + y\n\n"
    "\n"
    "def subtract(x, y):\n"
    "    z = x - y\n"
    "```\n\n"
    "---comment_chains ---\n"
    "```\n"
    "Please review this change.\n"
    "```\n\n"
    "---end_change_section ---\n\n"
    "### Example response\n\n"
    "22 - 23:\n"
    "The variable z is declared but then immediately returned. Consider returning the sum directly.\n"
    "```diff\n"
    "- [NEW]     z = x + y\n"
    "- [NEW]     return z\n"
    "+ [NEW]     return x + y\n"
    "```\n"
    "---\n"
    "## Changes made to `$filename` for your review\n\n"
    "REMINDER:\n"
    "- ONLY review lines marked with `[NEW]` in the `---new_hunk---` section\n"
    "- DO NOT review context lines (no `[NEW]` marker)\n"
    "- DO NOT review `---old_hunk---` section\n"
    "- Use EXACT line numbers shown when writing comments\n\n"
    "$patches"
)

COMMENT = string.Template(
    "A comment was made on a GitHub PR review for a diff hunk on a file - `$filename`. "
    "I would like you to follow the instructions in that comment.\n\n"
    "## GitHub PR Title\n\n"
    "`$title`\n\n"
    "## Description\n\n"
    "```\n"
    "$description\n"
    "```\n\n"
    "## Summary generated by the AI bot\n\n"
    "```\n"
    "$short_summary\n"
    "```\n\n"
    "## Diff being commented on\n\n"
    "DIFF-CONTEXT-BEGIN\n"
    "```diff\n"
    "$diff\n"
    "```\n"
    "DIFF-CONTEXT-END\n\n"
    "## File content\n\n"
    "```\n"
    "$file_content\n"
    "```"
    "## Instructions\n\n"
    "Please reply directly to the new comment (instead of suggesting a reply) and your reply will be posted as-is.\n\n"
    "If the comment contains instructions/requests for you, please comply. "
    "For example, if the comment is asking you to generate documentation comments on the code, "
    "in your reply please generate the required code.\n\n"
    'In your reply, please make sure to begin the reply by tagging the user with "@user".\n\n'
    "File content is provided only for your better understanding.\n\n"
    "## Comment format\n\n"
    "`user: comment`\n\n"
    "## Comment chain (including the new comment)\n\n"
    "PAY ATTENTION TO THE NEXT:\n"
    "Below is what user want you to do. Please dont forget, you act as a senior programmer,"
    "help the user with his demand:\n\n"
    "User want you to do this:\n\n"
    "```\n"
    "$comment_chain\n"
    "```\n\n"
    "Only focus in your answer on diff between: DIFF-CONTEXT-BEGIN and DIFF-CONTEXT-END:\n"
    "## The comment/request that you need to directly reply to\n\n"
    "```\n"
    "$comment\n"
    "```"
)
